# Travis configuration script

install: true

language: c

script: 
    - gcc numbers.c -o numbers.x
    - ./numbers.x

compilier: gcc

# Coverity addons

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Vz+J9Fycwaz3eJr5796fBnJzx4GtU1TmHZhnW1oogFJgFp3enpSBlnyKfjdFtQZhzEGpZr+CyS75FsQ0Yyh92KJE71cWvKVZgdrp9e9FfKS/0UxVOE+itwi1n9kowPdtbvfuphk+YjcI1ub+IcFsFRTg3e3c1RjVrW0uN4Jsgho3Jmg5ETFw5J1bOo+pP2vu6Zc1KizoOPggUR4qkPnsBVeTO7KSjHPg1nNeWBmNeCa/G4zIFPoIwC2TMUem110B4vaRpzsQsppUbvHbtw/3FHP/DqVrQaxYU0wERtmXcP7Zngt1P6JOsVY5KcqoBmbTAeC+6HLUXkNKuiHA8z7AyfloDOAq7LaqtLJ/Zigw+8WfDwmyqkXnhL0haYaR4doayQYlzoWxwxwq5PY+8tVrMEXCt8QZIX2FukzoC0CBWJ7bykhtfR3o5oGSukqE+vHtrhM3H/C18lS0bawE7tEjSQQVq2nTtZ6meftNEoQjlpYRpfSQnxve3eRz+OIjH8dIGe/ns8/3zCodcwq+k5FpMKt6byQ/zfPH97NAAb2kYGabi9Ymqazd1IMOK6krKmrrNYaf+CR0e6bofoHQPrIl4Wpf2kaxDtJEI4KAxqEkj8yy2DofFByN4IFPoPB7VgvhrLxKRuu4sS1cejoNHTn+wnlBJQPFyHF2mi5nYCnlhrw="

addons:
  coverity_scan:
    project:
      name: "rafiulhye/SCA-CITest"
      description: "<Your project description here>"
    notification_email: rafiul.hye@bjitgroup.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command:   "<Your build command here>"
    branch_pattern: coverity_scan
